Repository grtl/mysql-operator, pull requests merged in 2018-02, with the labels that each got.

#36 Create StatefulSet
  controller/cluster-controller.go
  controller/cluster-controller_test.go
  operator.go
  operator/cluster-operator.go
  pkg/apis/cr/v1/cluster.go
  testing/controller/cluster-controller.go
  testing/factory/cluster.go
Labels: koala-sprint

#44 Add test files to all packages to properly calculate coverage
  controller/cluster/controller.go
  operator/cluster/operator.go
  operator/cluster/operator_test.go
Labels: bug

#43 Update kubernetes libraries to 1.9.0
  .travis.yml
  Gopkg.lock
  operator/cluster/operator.go
Labels: enhancement

#53 Increase cluster controller logging
  controller/cluster/controller.go
  controller/cluster/controller_test.go
  controller/cluster/fake.go
  controller/cluster/logging.go
  controller/cluster/logging_test.go
  logging/cluster.go
  logging/cluster_test.go
  operator.go
  operator/cluster/fake.go
  operator/cluster/operator.go
Labels: dog-sprint, enhancement

#54 Create mysql config map during operator startup
  artifacts/mysql-crd.yaml
  crd/cluster.go
  crd/util.go
  operator.go
  operator/cluster/initialize.go
  util/crd.go
  util/file.go
Labels: dog-sprint, enhancement

#57 Make custom resource registration function generic
  crd/cluster.go
  crd/mysql.go
  crd/util.go
Labels: enhancement

#58 Make events hook generic for all controllers
  controller/cluster/controller_test.go
  controller/cluster/events.go
  controller/events.go
  controller/events_test.go
Labels: enhancement
