Repository grtl/mysql-operator, pull requests merged in 2018-03, with the labels that each got.

#61 Move controller base functions to seperate struct
  controller/base.go
  controller/base_test.go
  controller/cluster/controller.go
  controller/cluster/controller_test.go
Labels: enhancement

#65 Use secrets for providing MySQL password
  artifacts/mysql-statefulset.yaml
Labels: dog-sprint

#69 Fix Dockerfile artifacts
  Dockerfile
Labels: bug

#66 Create cluster read service
  operator/cluster/operator.go
Labels: ant-sprint, bug

#80 Update gitignore
  .gitignore
Labels: enhancement

#82 Template files distribution with the binary
  .travis.yml
  Dockerfile
  artifacts/artifacts.go
  hack/update-artifacts.sh
  hack/verify-artifacts.sh
  util/file.go
  util/template.go
Labels: enhancement

#81 Backup add
  artifacts/artifacts.go
  artifacts/backup-cronjob.yaml
  artifacts/backup-pvc.yaml
  controller/backup/controller.go
  operator/backup/operator.go
  pkg/apis/cr/v1/backup.go
  pkg/apis/cr/v1/zz_generated.deepcopy.go
Labels: ant-sprint

#90 Cluster restore from backup
  Gopkg.lock
  artifacts/artifacts.go
  artifacts/backup-cronjob.yaml
  artifacts/mysql-statefulset.yaml
  pkg/apis/cr/v1/cluster.go
  pkg/apis/cr/v1/zz_generated.deepcopy.go
Labels: ant-sprint

#91 Add cli binary to gitignore, fix lint errors
  .gitignore
  cli/cli
  cli/cmd/backup/backup.go
  cli/cmd/cluster/cluster.go
  controller/cluster/fake.go
  operator/cluster/fake.go
  pkg/apis/cr/v1/cluster.go
Labels: bug

#96 Provide kubeconfig and clientsets utility for cli
  cli/cmd/config/base.go
  cli/cmd/config/config.go
  cli/cmd/config/fake.go
  cli/cmd/root.go
Labels: cobra-sprint

#98 Default values for cluster fields
  artifacts/artifacts.go
  artifacts/mysql-service-read.yaml
  artifacts/mysql-service.yaml
  artifacts/mysql-statefulset.yaml
  controller/cluster/logging_test.go
  operator/cluster/operator.go
  pkg/apis/cr/v1/cluster.go
  testing/factory/cluster.go
  testing/factory/cluster_test.go
Labels: enhancement
